### ISSUE TITLE
[TASK] review app.init code in ticket

### ISSUE THREAD

**Issue by stuart909** [Pengin-Open-Source/pengin-pi#258]
**Description**
There is strange code in app.init that I approved because it was benign and I didn't notice it.  I have no idea why it is there.  The creator needs to provide context and understand that we are bringing in all blueprints from routes from the route folder's local variables if they are blueprint type.

**Details**
Home creator assign TT to self and review line 44 in app.init
```

# Inject global variables to templates
    @app.context_processor
    def inject_globals():
        company = model.Home.query.first() or DummyHome()
        name = company.company_name
        return dict(company_name=name)
```

**Comment by stuart909** [comment]
this ticket is to clean up app.init and enforce app.init standards.  We are not declaring overrides and configurations in app.init.  We are pulling in the packages and initializing a program.  All configs and overrides will be in the packages' config.py

**Comment by jkcswd** [comment]
This allows all jinja templates to access global variables (needed for the company name in the layout template as otherwise we would need to DB query and send the data on every route). Will split off into config file.
